### ISSUE TITLE
Scout unhandled exception

### ISSUE THREAD

**Issue by Rhinni** [themosis/themosis#118]
When I get an unhandled exception from within a scout template, I get a location and stack trace that are not very useful.

It just tells me the location in storage/views with the coded string, not the actual resources/view file

Example:
```
Unhandled Exception
Message:

Trying to get property of non-object

Location:

/var/www/themosis/storage/views/c7ae4ffad55c14cabb3f2ce37ba87e54 on line 29

Stack Trace:

#0 /var/www/themosis/htdocs/content/mu-plugins/themosis-framework/bootstrap/start.php(175): Themosis\Error\Error::native(8, 'Trying to get p...', '/var/www/themos...', 29)
#1 /var/www/themosis/storage/views/c7ae4ffad55c14cabb3f2ce37ba87e54(29): THFWK_Themosis->{closure}(8, 'Trying to get p...', '/var/www/themos...', 29, Array)
#2 /var/www/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/View/Engines/PhpEngine.php(36): include('/var/www/themos...')
#3 /var/www/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/View/Engines/ScoutEngine.php(55): Themosis\View\Engines\PhpEngine->evaluatePath('/var/www/themos...', Array)
#4 /var/www/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/View/View.php(109): Themosis\View\Engines\ScoutEngine->get('/var/www/themos...', Array)
#5 /var/www/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/View/View.php(92): Themosis\View\View->getContent()
#6 /var/www/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/View/View.php(69): Themosis\View\View->renderContent()
#7 /var/www/themosis/storage/views/a54546d3f1ed834a71647ea94e454b6c(10): Themosis\View\View->render()
#8 /var/www/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/View/Engines/PhpEngine.php(36): include('/var/www/themos...')
#9 /var/www/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/View/Engines/ScoutEngine.php(55): Themosis\View\Engines\PhpEngine->evaluatePath('/var/www/themos...', Array)
#10 /var/www/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/View/View.php(109): Themosis\View\Engines\ScoutEngine->get('/var/www/themos...', Array)
#11 /var/www/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/View/View.php(92): Themosis\View\View->getContent()
#12 /var/www/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/View/View.php(69): Themosis\View\View->renderContent()
#13 /var/www/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/View/View.php(288): Themosis\View\View->render()
#14 /var/www/themosis/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(422): Themosis\View\View->__toString()
#15 /var/www/themosis/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(202): Symfony\Component\HttpFoundation\Response->setContent(Object(Themosis\View\View))
#16 /var/www/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Route/Router.php(311): Symfony\Component\HttpFoundation\Response->__construct(Object(Themosis\View\View))
#17 /var/www/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Route/Router.php(283): Themosis\Route\Router->prepareResponse(Object(Themosis\Core\Request), Object(Themosis\View\View))
#18 /var/www/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Route/Router.php(249): Themosis\Route\Router->dispatchToRoute(Object(Themosis\Core\Request))
#19 /var/www/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Core/Application.php(238): Themosis\Route\Router->dispatch(Object(Themosis\Core\Request))
#20 /var/www/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Core/Application.php(223): Themosis\Core\Application->dispatch(Object(Themosis\Core\Request))
#21 /var/www/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Core/Application.php(207): Themosis\Core\Application->handle(Object(Themosis\Core\Request))
#22 /var/www/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Action/Action.php(109): Themosis\Core\Application->run('', NULL)
#23 /var/www/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Action/ActionNotifier.php(28): Themosis\Action\Action->run()
#24 /var/www/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Action/ActionSubject.php(27): Themosis\Action\ActionNotifier->update()
#25 /var/www/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Action/Action.php(96): Themosis\Action\ActionSubject->notify()
#26 [internal function]: Themosis\Action\Action->action('')
#27 /var/www/themosis/htdocs/cms/wp-includes/plugin.php(524): call_user_func_array(Array, Array)
#28 /var/www/themosis/htdocs/content/themes/scode-theme/bootstrap/start.php(224): do_action('themosis_run')
#29 /var/www/themosis/htdocs/content/themes/scode-theme/index.php(9): themosis_start_app()
#30 /var/www/themosis/htdocs/cms/wp-includes/template-loader.php(75): include('/var/www/themos...')
#31 /var/www/themosis/htdocs/cms/wp-blog-header.php(19): require_once('/var/www/themos...')
#32 /var/www/themosis/htdocs/index.php(11): require('/var/www/themos...')
#33 {main}
```

**Comment by jlambe** [comment]
In order to get proper debug message, use this code when dealing with your views:
```php
return View::make('myview')->render();
```

In place, this will return a string (compiled view) which if has an error, will give you the right message based on your view file and not the cached and compiled one.

**Comment by Rhinni** [comment]
I tried as you suggested which resulted in the same issue.

My controller:
```
class ContactController extends BaseController {

    protected $layout = 'pages.contact.contactIndex';

    protected function index($post, $query) {
        $this->layout->with('page', $post);
        return View::make('pages.contact.contactIndex')->render();
    }

}
```

In my view I on purpose produce the error with `echo $post->id;`

resulting in the Unhandled Exception with location of storage/views:

```
Unhandled Exception
Message:

Undefined variable: post

Location:

/var/www/themosis/storage/views/a54546d3f1ed834a71647ea94e454b6c on line 7

Stack Trace:

#0 /var/www/themosis/htdocs/content/mu-plugins/themosis-framework/bootstrap/start.php(175): Themosis\Error\Error::native(8, 'Undefined varia...', '/var/www/themos...', 7)
#1 /var/www/themosis/storage/views/a54546d3f1ed834a71647ea94e454b6c(7): THFWK_Themosis->{closure}(8, 'Undefined varia...', '/var/www/themos...', 7, Array)
#2 /var/www/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/View/Engines/PhpEngine.php(36): include('/var/www/themos...')
#3 /var/www/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/View/Engines/ScoutEngine.php(55): Themosis\View\Engines\PhpEngine->evaluatePath('/var/www/themos...', Array)
#4 /var/www/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/View/View.php(109): Themosis\View\Engines\ScoutEngine->get('/var/www/themos...', Array)
#5 /var/www/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/View/View.php(92): Themosis\View\View->getContent()
#6 /var/www/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/View/View.php(69): Themosis\View\View->renderContent()
#7 /var/www/themosis/htdocs/content/themes/scode-theme/resources/controllers/ContactController.php(9): Themosis\View\View->render()
#8 [internal function]: ContactController->index(Object(WP_Post), Object(WP_Query))
#9 /var/www/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Route/Controller.php(31): call_user_func_array(Array, Array)
#10 /var/www/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Route/ControllerDispatcher.php(77): Themosis\Route\Controller->callAction('index', Array)
#11 /var/www/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Route/ControllerDispatcher.php(49): Themosis\Route\ControllerDispatcher->call(Object(ContactController), Object(Themosis\Route\Route), 'index')
#12 /var/www/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Route/Router.php(201): Themosis\Route\ControllerDispatcher->dispatch(Object(Themosis\Route\Route), Object(Themosis\Core\Request), 'ContactControll...', 'index')
#13 [internal function]: Themosis\Route\Router->Themosis\Route\{closure}(Object(WP_Post), Object(WP_Query))
#14 /var/www/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Route/Route.php(221): call_user_func_array(Object(Closure), Array)
#15 /var/www/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Route/Router.php(275): Themosis\Route\Route->run()
#16 /var/www/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Route/Router.php(249): Themosis\Route\Router->dispatchToRoute(Object(Themosis\Core\Request))
#17 /var/www/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Core/Application.php(238): Themosis\Route\Router->dispatch(Object(Themosis\Core\Request))
#18 /var/www/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Core/Application.php(223): Themosis\Core\Application->dispatch(Object(Themosis\Core\Request))
#19 /var/www/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Core/Application.php(207): Themosis\Core\Application->handle(Object(Themosis\Core\Request))
#20 /var/www/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Action/Action.php(109): Themosis\Core\Application->run('', NULL)
#21 /var/www/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Action/ActionNotifier.php(28): Themosis\Action\Action->run()
#22 /var/www/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Action/ActionSubject.php(27): Themosis\Action\ActionNotifier->update()
#23 /var/www/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Action/Action.php(96): Themosis\Action\ActionSubject->notify()
#24 [internal function]: Themosis\Action\Action->action('')
#25 /var/www/themosis/htdocs/cms/wp-includes/plugin.php(524): call_user_func_array(Array, Array)
#26 /var/www/themosis/htdocs/content/themes/scode-theme/bootstrap/start.php(224): do_action('themosis_run')
#27 /var/www/themosis/htdocs/content/themes/scode-theme/index.php(9): themosis_start_app()
#28 /var/www/themosis/htdocs/cms/wp-includes/template-loader.php(75): include('/var/www/themos...')
#29 /var/www/themosis/htdocs/cms/wp-blog-header.php(19): require_once('/var/www/themos...')
#30 /var/www/themosis/htdocs/index.php(11): require('/var/www/themos...')
#31 {main}
```

**Comment by jlambe** [comment]
Weird, this isn't working and showing the correct view path.

**Comment by jlambe** [comment]
I'll try your code on newest version to see if this still persists. Unfortunately there is no other solution at the moment than rendering the view first before returning it.

**Comment by Rhinni** [comment]
Thank you for looking into it.

Also, is there a way to use `protected $layout = 'pages.contact.contactIndex';` in `return View::make('pages.contact.contactIndex')->render(); ` so I don't have to respecify `'pages.contact.contactIndex'`

For example:
`return View::make($this->layout->view)->render();`
or
`return View::make($this->layout->getView())->render();`

**Comment by jlambe** [comment]
Passing the layout string as a var should detect the correct view. Note that the $layout property is removed in the next release as it follows Illuminate/Routing controllers.
