### ISSUE TITLE
Route API without Themosis' theme

### ISSUE THREAD

**Issue by TipyTechnique** [themosis/themosis#242]
Hi,

I saw that we must bootstrap the core package by our own way to leverage the Route API.

How can i do this using a normal theme ?

I think if i'm only using your plugin boilerplate and write my code on it, i can use the Route API cause the plugin is bootstraping the core package. But i would like to use the app folder.

Thx for your time.

**Comment by TipyTechnique** [comment]
I tried to use route.php on the plugin, but it's not working.

I don't know where to put this code : 
`use App\Http\Kernel;
use Themosis\Core\Application;
$app = Application::getInstance();
$app->manage(Kernel::class, $app['request']);`

I tried some places, but i got this error : 
`[2019-01-10 16:42:33] local.ERROR: Cannot modify header information - headers already sent by (output started at /var/www/html/tipy-themosis/vendor/symfony/http-foundation/Response.php:1219) {"exception":"[object] (ErrorException(code: 0): Cannot modify header information - headers already sent by (output started at /var/www/html/tipy-themosis/vendor/symfony/http-foundation/Response.php:1219) at /var/www/html/tipy-themosis/htdocs/content/plugins/gravity-forms-video-creator/admin/class-gravity-forms-video-creator-admin-publications.php:995)
[stacktrace]
#0 [internal function]: Themosis\\Core\\Bootstrap\\ExceptionHandler->handleError(2, 'Cannot modify h...', '/var/www/html/t...', 995, Array)
#1 /var/www/html/tipy-themosis/htdocs/content/plugins/gravity-forms-video-creator/admin/class-gravity-forms-video-creator-admin-publications.php(995): header('P3P:CP=\"IDC DSP...')
#2 /var/www/html/tipy-themosis/htdocs/cms/wp-includes/class-wp-hook.php(286): Gravity_Forms_Video_Creator_Admin_Publications->my_start_session('')
#3 /var/www/html/tipy-themosis/htdocs/cms/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#4 /var/www/html/tipy-themosis/htdocs/cms/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#5 /var/www/html/tipy-themosis/htdocs/cms/wp-settings.php(467): do_action('init')
#6 /var/www/html/tipy-themosis/htdocs/wp-config.php(47): require_once('/var/www/html/t...')
#7 /var/www/html/tipy-themosis/htdocs/cms/wp-load.php(42): require_once('/var/www/html/t...')
#8 /var/www/html/tipy-themosis/htdocs/cms/wp-admin/admin-ajax.php(22): require_once('/var/www/html/t...')
#9 {main}
"} `

**Comment by TipyTechnique** [comment]
I think i made it works. I'll explain below how i did this if anyone has the same issue.

I checked the way you bootstraped the Route API on the 1.3 version to find how to do it.

So, we must bootstrap the application on this hook : template_redirect
On app/Hooks, i made an Hookable class to make this hook like this : 
```
    /**
     * Extend WordPress.
     */
    public function register()
    {
        try {
            // actions
            Action::add(
                'template_redirect',
                [$this, 'setRouter'],
                20
            );
        } catch (AssetException $e) {
            logger($e->getMessage());
        }
    }

    /**
     * Bootstrap application to leverage the Router API
     */
    public function setRouter()
    {
        if (is_feed() || is_comment_feed()) {
            return;
        }

        try {
            /**
             * Default WordPress template.
             *
             * By default, routes should be defined at application
             * root into the routes/web.php file.
             *
             * Routes can be overwritten using theme routes.php file.
             */
            $app = Application::getInstance();
            $app->manage(Kernel::class, $app['request']);
        } catch (\Exception $e) {
            // fallback wordpress templates
        }
    }
```

Then, we add our Hookable class on config/app.php and it's done :)
