### ISSUE TITLE
Can't use function with Action

### ISSUE THREAD

**Issue by lukechilds** [themosis/themosis#88]
In [the docs](http://framework.themosis.com/docs/action/) it says you can use functions with the `Action` class.

If I do:

```php
function savePostTest($post_id) {
  var_dump($post_id);
  exit;
}

Action::add('save_post', 'savePostTest');
```

I get the following error:
```
Unhandled Exception

Message:

Class savePostTest does not exist
Location:

/vagrant/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Core/Container.php on line 281
Stack Trace:

#0 /vagrant/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Core/Container.php(281): ReflectionClass->__construct('savePostTest')
#1 /vagrant/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Core/Container.php(162): Themosis\Core\Container->build('savePostTest', Array)
#2 /vagrant/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Action/ActionBuilder.php(132): Themosis\Core\Container->make('savePostTest')
#3 /vagrant/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Action/ActionBuilder.php(114): Themosis\Action\ActionBuilder->buildClassEventCallback('savePostTest', 'save_post')
#4 /vagrant/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Action/ActionBuilder.php(99): Themosis\Action\ActionBuilder->addClassEvent('save_post', 'savePostTest', 10, 3)
#5 /vagrant/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Action/ActionBuilder.php(39): Themosis\Action\ActionBuilder->addActionEvent('save_post', 'savePostTest', 10, 3)
#6 [internal function]: Themosis\Action\ActionBuilder->add('save_post', 'savePostTest')
#7 /vagrant/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Facades/Facade.php(107): call_user_func_array(Array, Array)
#8 /vagrant/themosis/htdocs/content/themes/memorialise/resources/admin/memorial.php(51): Themosis\Facades\Facade::__callStatic('add', Array)
#9 /vagrant/themosis/htdocs/content/themes/memorialise/resources/admin/memorial.php(51): Themosis\Facades\Action::add('save_post', 'savePostTest')
#10 /vagrant/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Core/Loader.php(58): include_once('/vagrant/themos...')
#11 /vagrant/themosis/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Core/AdminLoader.php(8): Themosis\Core\Loader->append('/vagrant/themos...')
#12 /vagrant/themosis/htdocs/content/themes/memorialise/bootstrap/start.php(123): Themosis\Core\AdminLoader->__construct('/vagrant/themos...')
#13 /vagrant/themosis/htdocs/content/themes/memorialise/functions.php(162): require_once('/vagrant/themos...')
#14 /vagrant/themosis/htdocs/cms/wp-settings.php(369): include('/vagrant/themos...')
#15 /vagrant/themosis/htdocs/wp-config.php(16): require_once('/vagrant/themos...')
#16 /vagrant/themosis/htdocs/cms/wp-load.php(42): require_once('/vagrant/themos...')
#17 /vagrant/themosis/htdocs/cms/wp-admin/admin.php(31): require_once('/vagrant/themos...')
#18 /vagrant/themosis/htdocs/cms/wp-admin/post.php(12): require_once('/vagrant/themos...')
#19 {main}
```
However, this works:
```php
function savePostTest($post_id) {
  var_dump($post_id);
  exit;
}

add_action('save_post', 'savePostTest');
```

**Comment by jlambe** [comment]
If using the `Action` facade, it will look after a class in place of a function. You can pass a closure but no user functions.
For example, your code `Action::add('save_post', 'savePostTest')`  will look after the class `savePostTest` and its method `save_post`.
If you do not intend to use a class, stick with the default `add_action` function. It would probably worth tell it into the docs.
