### ISSUE TITLE
Error when activating BuddyPress with Themosis

### ISSUE THREAD

**Issue by lougreenwood** [themosis/themosis#97]
Installed and activated Buddypress from WP plugin directory, get the following error:

```
Unhandled Exception
Message:
bp_setup_current_user was called incorrectly. The current user is being initialized without using $wp->init().
===
Trace:
#6 /Users/Lou/Dropbox/MyProject/htdocs/content/plugins/pods/classes/PodsView.php(197): pods_is_admin()
#7 /Users/Lou/Dropbox/MyProject/htdocs/content/plugins/pods/includes/general.php(1398): PodsView::get('pods_components...', 'transient', '', NULL)
#8 /Users/Lou/Dropbox/MyProject/htdocs/content/plugins/pods/includes/general.php(1501): pods_view_get('pods_components', 'transient', '', NULL)
#9 /Users/Lou/Dropbox/MyProject/htdocs/content/plugins/pods/classes/PodsComponents.php(308): pods_transient_get('pods_components')
#10 /Users/Lou/Dropbox/MyProject/htdocs/cms/wp-includes/plugin.php(525): PodsComponents->get_components('')
#11 /Users/Lou/Dropbox/MyProject/htdocs/cms/wp-settings.php(340): do_action('setup_theme')
#12 /Users/Lou/Dropbox/MyProject/htdocs/wp-config.php(16): require_once('/Users/Lou/Drop...')
#13 /Users/Lou/Dropbox/MyProject/htdocs/cms/wp-load.php(42): require_once('/Users/Lou/Drop...')
#14 /Users/Lou/Dropbox/MyProject/htdocs/cms/wp-admin/admin.php(31): require_once('/Users/Lou/Drop...')
#15 /Users/Lou/Dropbox/MyProject/htdocs/cms/wp-admin/update.php(13): require_once('/Users/Lou/Drop...')
#16 {main}
===
 Please see Debugging in WordPress for more information. (This message was added in version 1.7.)
Location:
/Users/Lou/Dropbox/MyProject/htdocs/cms/wp-includes/functions.php on line 3897
Stack Trace:
#0 /Users/Lou/Dropbox/MyProject/htdocs/content/mu-plugins/themosis-framework/bootstrap/start.php(175): Themosis\Error\Error::native(1024, 'bp_setup_curren...', '/Users/Lou/Drop...', 3897)
#1 [internal function]: THFWK_Themosis->{closure}(1024, 'bp_setup_curren...', '/Users/Lou/Drop...', 3897, Array)
#2 /Users/Lou/Dropbox/MyProject/htdocs/cms/wp-includes/functions.php(3897): trigger_error('bp_setup_curren...')
#3 /Users/Lou/Dropbox/MyProject/htdocs/content/plugins/buddypress/bp-core/bp-core-dependency.php(230): _doing_it_wrong('bp_setup_curren...', 'The current use...', '(This message w...')
#4 /Users/Lou/Dropbox/MyProject/htdocs/cms/wp-includes/plugin.php(525): bp_setup_current_user('')
#5 /Users/Lou/Dropbox/MyProject/htdocs/cms/wp-includes/pluggable.php(47): do_action('set_current_use...')
#6 /Users/Lou/Dropbox/MyProject/htdocs/cms/wp-includes/user.php(2475): wp_set_current_user(3)
#7 /Users/Lou/Dropbox/MyProject/htdocs/cms/wp-includes/pluggable.php(69): _wp_get_current_user()
#8 /Users/Lou/Dropbox/MyProject/htdocs/cms/wp-includes/pluggable.php(950): wp_get_current_user()
#9 /Users/Lou/Dropbox/MyProject/htdocs/content/plugins/pods/includes/general.php(230): is_user_logged_in()
#10 /Users/Lou/Dropbox/MyProject/htdocs/content/plugins/pods/classes/PodsView.php(197): pods_is_admin()
#11 /Users/Lou/Dropbox/MyProject/htdocs/content/plugins/pods/includes/general.php(1398): PodsView::get('pods_components...', 'transient', '', NULL)
#12 /Users/Lou/Dropbox/MyProject/htdocs/content/plugins/pods/includes/general.php(1501): pods_view_get('pods_components', 'transient', '', NULL)
#13 /Users/Lou/Dropbox/MyProject/htdocs/content/plugins/pods/classes/PodsComponents.php(308): pods_transient_get('pods_components')
#14 /Users/Lou/Dropbox/MyProject/htdocs/cms/wp-includes/plugin.php(525): PodsComponents->get_components('')
#15 /Users/Lou/Dropbox/MyProject/htdocs/cms/wp-settings.php(340): do_action('setup_theme')
#16 /Users/Lou/Dropbox/MyProject/htdocs/wp-config.php(16): require_once('/Users/Lou/Drop...')
#17 /Users/Lou/Dropbox/MyProject/htdocs/cms/wp-load.php(42): require_once('/Users/Lou/Drop...')
#18 /Users/Lou/Dropbox/MyProject/htdocs/cms/wp-admin/admin.php(31): require_once('/Users/Lou/Drop...')
#19 /Users/Lou/Dropbox/MyProject/htdocs/cms/wp-admin/update.php(13): require_once('/Users/Lou/Drop...')
#20 {main}
```

**Comment by lougreenwood** [comment]
Here's the error again when I disable the 'Pods' plugin:

Running WP 4.5.3 & BP 2.6.1

```
Message:
bp_setup_current_user was called incorrectly. The current user is being initialized without using $wp->init().
===
Trace:
#6 /Users/Lou/Dropbox/MyProject/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Core/Container.php(278): Themosis\Metabox\MetaboxIgniterService->Themosis\Metabox\{closure}(Object(Themosis\Core\Application), Array)
#7 /Users/Lou/Dropbox/MyProject/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Core/Container.php(162): Themosis\Core\Container->build(Object(Closure), Array)
#8 /Users/Lou/Dropbox/MyProject/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Core/Container.php(644): Themosis\Core\Container->make('metabox')
#9 /Users/Lou/Dropbox/MyProject/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Facades/Facade.php(57): Themosis\Core\Container->offsetGet('metabox')
#10 /Users/Lou/Dropbox/MyProject/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Facades/Facade.php(43): Themosis\Facades\Facade::resolveFacadeInstance('metabox')
#11 /Users/Lou/Dropbox/MyProject/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Facades/Facade.php(102): Themosis\Facades\Facade::getFacadeRoot()
#12 /Users/Lou/Dropbox/MyProject/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Configuration/Template.php(33): Themosis\Facades\Facade::__callStatic('make', Array)
#13 /Users/Lou/Dropbox/MyProject/htdocs/content/themes/dental-cpd-pro/bootstrap/start.php(77): Themosis\Configuration\Template->make()
#14 /Users/Lou/Dropbox/MyProject/htdocs/content/themes/dental-cpd-pro/functions.php(162): require_once('/Users/Lou/Drop...')
#15 /Users/Lou/Dropbox/MyProject/htdocs/cms/wp-settings.php(369): include('/Users/Lou/Drop...')
#16 /Users/Lou/Dropbox/MyProject/htdocs/wp-config.php(16): require_once('/Users/Lou/Drop...')
#17 /Users/Lou/Dropbox/MyProject/htdocs/cms/wp-load.php(42): require_once('/Users/Lou/Drop...')
#18 /Users/Lou/Dropbox/MyProject/htdocs/cms/wp-admin/admin.php(31): require_once('/Users/Lou/Drop...')
#19 /Users/Lou/Dropbox/MyProject/htdocs/cms/wp-admin/update.php(13): require_once('/Users/Lou/Drop...')
#20 {main}
===
 Please see Debugging in WordPress for more information. (This message was added in version 1.7.)
Location:
/Users/Lou/Dropbox/MyProject/htdocs/cms/wp-includes/functions.php on line 3897
Stack Trace:
#0 /Users/Lou/Dropbox/MyProject/htdocs/content/mu-plugins/themosis-framework/bootstrap/start.php(175): Themosis\Error\Error::native(1024, 'bp_setup_curren...', '/Users/Lou/Drop...', 3897)
#1 [internal function]: THFWK_Themosis->{closure}(1024, 'bp_setup_curren...', '/Users/Lou/Drop...', 3897, Array)
#2 /Users/Lou/Dropbox/MyProject/htdocs/cms/wp-includes/functions.php(3897): trigger_error('bp_setup_curren...')
#3 /Users/Lou/Dropbox/MyProject/htdocs/content/plugins/buddypress/bp-core/bp-core-dependency.php(230): _doing_it_wrong('bp_setup_curren...', 'The current use...', '(This message w...')
#4 /Users/Lou/Dropbox/MyProject/htdocs/cms/wp-includes/plugin.php(525): bp_setup_current_user('')
#5 /Users/Lou/Dropbox/MyProject/htdocs/cms/wp-includes/pluggable.php(47): do_action('set_current_use...')
#6 /Users/Lou/Dropbox/MyProject/htdocs/cms/wp-includes/user.php(2475): wp_set_current_user(3)
#7 /Users/Lou/Dropbox/MyProject/htdocs/cms/wp-includes/pluggable.php(69): _wp_get_current_user()
#8 /Users/Lou/Dropbox/MyProject/htdocs/content/mu-plugins/themosis-framework/src/Themosis/User/UserFactory.php(122): wp_get_current_user()
#9 /Users/Lou/Dropbox/MyProject/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Metabox/MetaboxIgniterService.php(22): Themosis\User\UserFactory->current()
#10 /Users/Lou/Dropbox/MyProject/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Core/Container.php(278): Themosis\Metabox\MetaboxIgniterService->Themosis\Metabox\{closure}(Object(Themosis\Core\Application), Array)
#11 /Users/Lou/Dropbox/MyProject/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Core/Container.php(162): Themosis\Core\Container->build(Object(Closure), Array)
#12 /Users/Lou/Dropbox/MyProject/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Core/Container.php(644): Themosis\Core\Container->make('metabox')
#13 /Users/Lou/Dropbox/MyProject/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Facades/Facade.php(57): Themosis\Core\Container->offsetGet('metabox')
#14 /Users/Lou/Dropbox/MyProject/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Facades/Facade.php(43): Themosis\Facades\Facade::resolveFacadeInstance('metabox')
#15 /Users/Lou/Dropbox/MyProject/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Facades/Facade.php(102): Themosis\Facades\Facade::getFacadeRoot()
#16 /Users/Lou/Dropbox/MyProject/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Configuration/Template.php(33): Themosis\Facades\Facade::__callStatic('make', Array)
#17 /Users/Lou/Dropbox/MyProject/htdocs/content/themes/dental-cpd-pro/bootstrap/start.php(77): Themosis\Configuration\Template->make()
#18 /Users/Lou/Dropbox/MyProject/htdocs/content/themes/dental-cpd-pro/functions.php(162): require_once('/Users/Lou/Drop...')
#19 /Users/Lou/Dropbox/MyProject/htdocs/cms/wp-settings.php(369): include('/Users/Lou/Drop...')
#20 /Users/Lou/Dropbox/MyProject/htdocs/wp-config.php(16): require_once('/Users/Lou/Drop...')
#21 /Users/Lou/Dropbox/MyProject/htdocs/cms/wp-load.php(42): require_once('/Users/Lou/Drop...')
#22 /Users/Lou/Dropbox/MyProject/htdocs/cms/wp-admin/admin.php(31): require_once('/Users/Lou/Drop...')
#23 /Users/Lou/Dropbox/MyProject/htdocs/cms/wp-admin/update.php(13): require_once('/Users/Lou/Drop...')
#24 {main}
```

**Comment by jlambe** [comment]
Hi,
it's an error thrown by BuddyPress. In order to stop getting those alerts, set your local environment to not handle them by setting to false the constants located in your `config/environments/local.php` file (WP_DEBUG, THEMOSIS_ERROR_DISPLAY, ...)
Note that these errors are only showed to you on a local environment. On staging or production, errors are not shown by default.

**Comment by lougreenwood** [comment]
Hi, thanks for your reply.

Setting the following to false gives me white screen, no errors in php error log:

define('THEMOSIS_ERROR_DISPLAY', false);
define('THEMOSIS_ERROR_SHUTDOWN', false);
define('THEMOSIS_ERROR_REPORT', -1);

Also, assuming the above worked, would this mean that to run BP on my dev environment I lose access to Themosis error reporting?

**Comment by jlambe** [comment]
But be sure to set `THEMOSIS_ERROR_REPORT` to `0` to avoid the white screen.

You're loosing error reporting indeed. If this is only happening on a specific screen perhaps you can accommodate for local development but it's not ideal. I suggest you to also report the error to the BuddyPress team and perhaps fix it yourself if you have time.

**Comment by lougreenwood** [comment]
I also tried `THEMOSIS_ERROR_REPORT` at `0`, but still get white screen.

I'm confused why this is a BP issue when BP works fine using the same WP db in a normal WP (non-themosis) instance, but all wp-admin and public pages error/whitescreen with the same db/setup when used in Themosis.

**Comment by jlambe** [comment]
And you set all other WP_DEBUG constants to false as well?
By default, on a classic WordPress install, debugging is not active so that's why it's working.

**Comment by lougreenwood** [comment]
Yep, here's my local.php:

```
// Development
define('SAVEQUERIES', false);
define('WP_DEBUG', false);
define('SCRIPT_DEBUG', false);

// Themosis framework
define('THEMOSIS_ERROR_DISPLAY', false);
define('THEMOSIS_ERROR_SHUTDOWN', false);
define('THEMOSIS_ERROR_REPORT', 0);
```

**Comment by lougreenwood** [comment]
I've also disabled all plugins except BP, same issue.

**Comment by jlambe** [comment]
This is not normal behavior. I'll need to test it on a new instance and check if I have same issues.
I won't have time to test it on the following weeks but I'll try to give you seedback as soon as possible.
I can't give you more solution that try to fix the BuddyPress issue by checking the line code where the issue is triggered and perhaps fix it until it is done on the plugin and report it as well.

**Comment by Rhinni** [comment]
Perhaps upgrading to the latest version of Themosis might help? At least it looks like @lougreenwood is running 1.2.* and not 1.3.0
